// Terms of Service — public route. A minimal, readable MVP terms page (not
// legal-heavy) covering what Onboardly is, user responsibilities, AI accuracy,
// secrets, data usage, the no-warranty disclaimer, and a contact placeholder.
// Linked from the login and register pages.

import Link from "next/link";
import type { Metadata } from "next";
import { ArrowLeft } from "lucide-react";
import { AppIcon } from "@/components/layout/AppIcon";
import { ThemeToggle } from "@/components/theme/ThemeToggle";

export const metadata: Metadata = {
  title: "Terms of Service · Onboardly",
  description:
    "The terms that apply when you use Onboardly, the AI onboarding assistant.",
};

const LAST_UPDATED = "June 2026";

interface Section {
  heading: string;
  body: string;
}

const SECTIONS: Section[] = [
  {
    heading: "1. What Onboardly is",
    body: "Onboardly is an AI onboarding assistant. It generates personalized onboarding plans and answers questions grounded in the content you connect — your project documents, GitHub repositories, and synced sources — with citations back to that material.",
  },
  {
    heading: "2. Your content and connected sources",
    body: "You are responsible for the projects, workspaces, repositories, and documents you connect to Onboardly, and for having the right to connect them. You are responsible for the activity that happens under your account.",
  },
  {
    heading: "3. AI answers may be imperfect",
    body: "Answers are generated by AI and may be incomplete, outdated, or incorrect. Treat them as a starting point, not authoritative guidance, and verify anything important against the cited source before you rely on it.",
  },
  {
    heading: "4. Don't upload secrets",
    body: "Do not upload sensitive secrets, private credentials, API keys, or personal data you are not authorized to share. Onboardly is designed for onboarding knowledge, not secret storage.",
  },
  {
    heading: "5. How we use connected data",
    body: "GitHub and Slack data you connect is used only to provide Onboardly's onboarding and knowledge features — building your knowledge base, generating courses, and answering your questions. It is not sold.",
  },
  {
    heading: "6. No warranty (MVP)",
    body: "Onboardly is an early-stage product provided “as is,” without warranties of any kind. Features may change or break, and availability is not guaranteed. Use it at your own discretion.",
  },
  {
    heading: "7. Contact",
    body: "Questions about these terms? Reach out at hello@onboardly.example (placeholder contact for this MVP).",
  },
];

export default function TermsPage() {
  return (
    <main className="bg-background min-h-svh">
      <header className="border-border bg-background/85 sticky top-0 z-20 border-b backdrop-blur">
        <div className="mx-auto flex w-full max-w-3xl items-center justify-between px-4 py-3 sm:px-6">
          <Link
            href="/"
            className="font-heading flex items-center gap-2 text-base font-semibold tracking-tight"
          >
            <AppIcon className="size-7" />
            Onboardly
          </Link>
          <ThemeToggle />
        </div>
      </header>

      <article className="mx-auto w-full max-w-3xl px-4 py-10 sm:px-6 sm:py-14">
        <Link
          href="/login"
          className="text-muted-foreground hover:text-foreground -ml-1 inline-flex items-center gap-1.5 text-sm transition-colors"
        >
          <ArrowLeft className="size-4" />
          Back to sign in
        </Link>

        <h1 className="font-heading mt-6 text-3xl font-semibold tracking-tight">
          Terms of Service
        </h1>
        <p className="text-muted-foreground mt-2 text-sm">
          Last updated {LAST_UPDATED}
        </p>
        <p className="text-muted-foreground mt-4 text-sm leading-7">
          These terms describe the basics of using Onboardly. We&apos;ve kept
          them short and readable. By using Onboardly you agree to them.
        </p>

        <div className="mt-8 space-y-8">
          {SECTIONS.map((section) => (
            <section key={section.heading}>
              <h2 className="font-heading text-lg font-semibold tracking-tight">
                {section.heading}
              </h2>
              <p className="text-muted-foreground mt-2 text-sm leading-7">
                {section.body}
              </p>
            </section>
          ))}
        </div>

        <div className="border-border mt-12 border-t pt-6 text-sm">
          <Link
            href="/register"
            className="text-primary font-medium hover:underline"
          >
            Create your account
          </Link>
          <span className="text-muted-foreground">
            {" "}
            or{" "}
            <Link href="/login" className="hover:text-foreground underline underline-offset-2">
              sign in
            </Link>
            .
          </span>
        </div>
      </article>
    </main>
  );
}
